version: "3.9"
services:
  www:
    image: hellohappyw0rld/hospital-app:${BUILD_NUMBER:-latest}
    # Use the image that Jenkins already built and pushed
    environment:
      APP_ENV: staging
      DB_HOST: db
    ports:
      - "8081:80"

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
